### ISSUE TITLE
Documentation : update missing step before launch

### ISSUE THREAD

**Issue by nymeku** [Oriun/epitech-competencies-stats#1]
There is missing step in the tutorial after cloning

**Comment by nymeku** [comment]
le bloc manquant 

1. Clonez le repo ou téléchargez et décompressez la dernière release.
2. Si vous avez cloné le repo :

```console
cd popup
yarn
yarn build
```

3. Ouvrez Chrome et allez à `chrome://extensions/`.
4. Activez le mode `Développeur` (case à cocher dans le coin supérieur droit).
5. Cliquez sur `Charger l'extension non empaquetée...` et sélectionnez le dossier cloné/téléchargé.

**Comment by nymeku** [comment]
a copier en mode raw de github !

**Comment by Oriun** [comment]
Nice, merci pour la correction, je vais intégrer ça au readme 👌

**Comment by Oriun** [comment]
NB: J'ai remplacé `yarn` par `pnpm` car c'est le package manager que j'utilise sur ce projet
